---
title: "Plotly Examples"
output: 
   html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r, include=FALSE}
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

```{r plotly scatterplot}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, '\nRating: ',rating)) %>% 
   plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

show only the neighborhoods with the most rentals.

```{r}
common_neighborhoods = 
  nyc_airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% top_n(8) %>% select(neighbourhood)

common_neighborhoods =
  nyc_airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)

inner_join(nyc_airbnb, common_neighborhoods, by = "neighbourhood") %>% 
 mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type ="box", colors = "Set2")
  
```


